### ISSUE TITLE
README.md should briefly describe the difference between goals

### ISSUE THREAD

**Issue by bmarwell** [CycloneDX/cyclonedx-maven-plugin#207] opened 2022-09-12 11:50 UTC
> The CycloneDX Maven plugin contains the following three goals:
> 
> * makeBom
> * makeAggregateBom
> * makePackageBom

But it doesn't tell the user anything about the use case of each goal and when to use which.

**Comment by msymons** [comment] 2022-09-26 13:17
Duplicate of #13

**Closed** 2023-02-02 22:31 UTC
