### ISSUE TITLE
Portions of bom.xml not pretty printed

### ISSUE THREAD

**Issue by davewichers** [CycloneDX/cyclonedx-maven-plugin#93] opened 2021-03-25 23:04 UTC
When I look at the bom.xml file generated for AntiSamy, most of it looks nice, well-formatted, indented. But two sections aren't:

`<externalReferences><reference type="issue-tracker"><url>https://issues.apache.org/jira/browse/CODEC</url></reference><reference type="vcs"><url>https://github.com/apache/commons-codec</url></reference><reference type="build-system"><url>https://builds.apache.org/</url></reference><reference type="mailing-list"><url>https://mail-archives.apache.org/mod_mbox/commons-user/</url></reference><reference type="website"><url>https://www.apache.org/</url></reference><reference type="distribution"><url>https://repository.apache.org/service/local/staging/deploy/maven2</url></reference></externalReferences>`

and

`</components><dependencies><dependency ref="pkg:maven/commons-codec/commons-codec@1.15?type=jar"/><dependency ref="pkg:maven/net.sourceforge.nekohtml/nekohtml@1.9.22?type=jar"/><dependency ref="pkg:maven/org.apache.httpcomponents/httpclient@4.5.13?type=jar"><dependency ref="pkg:maven/commons-logging/commons-logging@1.2?type=jar"/></dependency><dependency ref="pkg:maven/commons-logging/commons-logging@1.2?type=jar"/><dependency ref="pkg:maven/org.apache.httpcomponents/httpcore@4.4.14?type=jar"/><dependency ref="pkg:maven/org.apache.xmlgraphics/batik-css@1.14?type=jar"><dependency ref="pkg:maven/org.apache.xmlgraphics/batik-shared-resources@1.14?type=jar"/><dependency ref="pkg:maven/org.apache.xmlgraphics/batik-util@1.14?type=jar"/><dependency ref="pkg:maven/org.apache.xmlgraphics/xmlgraphics-commons@2.6?type=jar"/></dependency><dependency ref="pkg:maven/org.apache.xmlgraphics/batik-shared-resources@1.14?type=jar"/><dependency ref="pkg:maven/org.apache.xmlgraphics/batik-util@1.14?type=jar"><dependency ref="pkg:maven/org.apache.xmlgraphics/batik-constants@1.14?type=jar"/><dependency ref="pkg:maven/org.apache.xmlgraphics/batik-i18n@1.14?type=jar"/></dependency><dependency ref="pkg:maven/org.apache.xmlgraphics/batik-constants@1.14?type=jar"/><dependency ref="pkg:maven/org.apache.xmlgraphics/batik-i18n@1.14?type=jar"/><dependency ref="pkg:maven/org.apache.xmlgraphics/xmlgraphics-commons@2.6?type=jar"><dependency ref="pkg:maven/commons-io/commons-io@1.3.1?type=jar"/></dependency><dependency ref="pkg:maven/commons-io/commons-io@1.3.1?type=jar"/><dependency ref="pkg:maven/org.slf4j/slf4j-api@1.7.30?type=jar"/><dependency ref="pkg:maven/org.slf4j/slf4j-simple@1.7.30?type=jar"/><dependency ref="pkg:maven/xerces/xercesImpl@2.12.1?type=jar"/><dependency ref="pkg:maven/xml-apis/xml-apis@1.4.01?type=jar"/><dependency ref="pkg:maven/xml-apis/xml-apis-ext@1.3.04?type=jar"/><dependency ref="pkg:maven/com.github.spotbugs/spotbugs-annotations@4.2.2?type=jar"><dependency ref="pkg:maven/com.google.code.findbugs/jsr305@3.0.2?type=jar"/></dependency><dependency ref="pkg:maven/com.google.code.findbugs/jsr305@3.0.2?type=jar"/>
477 </dependencies>`

Can cyclonedx or cyclonedx-maven-plugin be enhanced to format these sections nicely like the rest of the BOM? I suspect the actual formatting issue isn't in the plugin itself, but I could be wrong.

**Comment by stevespringett** [comment] 2021-03-25 23:10
Duplicate of #88

**Closed by stevespringett** 2021-03-25 23:10 UTC
Labels: duplicate

**Comment by davewichers** [comment] 2021-03-25 23:53
I don't think this is exactly a duplicate of #88 as it affects the XML, not JSON, and it affects the XML in more places than is described in the JSON ticket.

**Comment by DarthHater** [comment] 2021-03-26 23:14
I addressed the `dependency` section of this in: https://github.com/CycloneDX/cyclonedx-core-java/pull/84
