### ISSUE TITLE
version 2.4.0 throws "Unknown host cyclonedx.org" error

### ISSUE THREAD

**Issue by F242MX** [CycloneDX/cyclonedx-maven-plugin#94] opened 2021-04-01 13:16 UTC
This is what I get when I try to use cyclonedx 2.4.0:

[ERROR] Failed to execute goal org.cyclonedx:cyclonedx-maven-plugin:2.4.0:makeAggregateBom (default-cli) on project XXX: Execution default-cli of goal org.cyclonedx:cyclonedx-maven-plugin:2.4.0:makeAggregateBom failed: java.net.UnknownHostException: cyclonedx.org: Unknown host cyclonedx.org -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

Note that if I downgrade to cyclonedx version 2.3.0, then it works fine.

**Comment by stevespringett** [comment] 2021-04-01 13:52
Caused by: https://github.com/CycloneDX/cyclonedx-core-java/issues/87

**Comment by stevespringett** [comment] 2021-04-09 05:06
Resolved in 2.4.2

**Closed by stevespringett** 2021-04-09 05:06 UTC
