### ISSUE TITLE
Stuck when running in offline environment

### ISSUE THREAD

**Issue by F242MX** [CycloneDX/cyclonedx-maven-plugin#74] opened 2020-12-08 16:56 UTC
The plugin cyclonedx-maven-plugin seems to require an access to internet in order to fail to download a dependency.

I would summarize the issue in two points : 

1 - In an offline environment, the plugin is stuck and prints messages : 
"ERROR org.spdx.rdfparser.license.ListedLicenses - I/O error opening Json TOC URL, using local TOC file"
"WARNING org.spdx.rdfparser.license.ListedLicenses  - Unable to open SPDX listed license model.  Using local file copy for SPDX listed licenses"
These messages are repeated multiple times, but the delay between these error messages rapidly increases.
Eventually, after hours the operation is still not completed because the plugin still tries to access this online resource.

2 - In an online environment, the plugin still fails to access this online ressource but prints rapidly the error messages described in the point 1.
It is then able to fallback to the local copy of the file and the operation completes.

My questions are : 
1 - If this online resource (TOC file) is normally required why is it not accessible in an online environment?
2 - Is there a way to pass an option in order to disable the querying of this online file and to directly fallback to the local file so that the operation of the plugin is not stuck anymore in an offline environment?

**Comment by stevespringett** [comment] 2020-12-08 16:59
Duplicate of #42 and #50.

Also, current versions of the maven plugin no longer use the SPDX library, so non-issue.

**Comment by F242MX** [comment] 2020-12-08 17:24
Thank you a lot :)

I had not seen these previous issues, I will try to follow these instructions to get rid of our problem.

It is true that we are stuck to an old version (v1.6.4) because newer versions of cyclonedx-maven-plugin require another online dependency that we strugle to get in our offline environment as documented in the issue : 
https://github.com/CycloneDX/cyclonedx-maven-plugin/issues/54

**Closed** 2021-01-30 22:56 UTC
Labels: duplicate
