### ISSUE TITLE
Attempting to download JSon Scheme fails.

### ISSUE THREAD

**Issue by wrgoff** [CycloneDX/cyclonedx-maven-plugin#63] opened 2020-08-26 15:30 UTC
Attempting to create Boms as part of a gitlab project, using the maven plugin.  The plugin attempts to download the "com.github.everit-org.json-schema:org.everit.json.schema:jar:1.12.1" from https://repo.maven.apache.org/maven2.

```xml
			<plugin>
				<groupId>org.cyclonedx</groupId>
				<artifactId>cyclonedx-maven-plugin</artifactId>
				<version>2.0.3</version>
				<executions>
					<execution>
						<phase>verify</phase>
						<goals>
							<goal>makeAggregateBom</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<projectType>library</projectType>
					<schemaVersion>1.2</schemaVersion>
					<includeBomSerialNumber>true</includeBomSerialNumber>
					<includeCompileScope>true</includeCompileScope>
					<includeProvidedScope>true</includeProvidedScope>
					<includeRuntimeScope>true</includeRuntimeScope>
					<includeSystemScope>true</includeSystemScope>
					<includeTestScope>true</includeTestScope>
					<includeLicenseText>false</includeLicenseText>
					<outputFormat>all</outputFormat>
				</configuration>
			</plugin>
```

This of course doesn't exist.  Ie. "https://repo.maven.apache.org/maven2/com/github/everit-org/json-schema/org.everit.json.schema/1.12.1/org.everit.json.schema-1.12.1.jar"  throws a 404.  And thus the build fails.

 [ERROR] Failed to execute goal org.cyclonedx:cyclonedx-maven-plugin:2.0.3:makeAggregateBom (default) on project LicenseService: Execution default of goal org.cyclonedx:cyclonedx-maven-plugin:2.0.3:makeAggregateBom failed: Plugin org.cyclonedx:cyclonedx-maven-plugin:2.0.3 or one of its dependencies could not be resolved: Could not transfer artifact com.github.everit-org.json-schema:org.everit.json.schema:jar:1.12.1 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/com/github/everit-org/json-schema/org.everit.json.schema/1.12.1/org.everit.json.schema-1.12.1.jar: Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.208.215] failed: Connection timed out (Connection timed out) -> [Help 1]

Any ideas?

**Comment by coderpatros** [comment] 2020-08-26 19:08
Hi @wrgoff, this looks like a duplicate of https://github.com/CycloneDX/cyclonedx-maven-plugin/issues/54?

**Closed** 2020-09-23 15:27 UTC
