### ISSUE TITLE
Skip SPDX licence check

### ISSUE THREAD

**Issue by siewer** [CycloneDX/cyclonedx-maven-plugin#50] opened 2020-03-26 11:41 UTC
I am running bom generation in command line with

mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom

is it possible to somehow disable SPDX licence verification? CI slaves I am using have no possibility to connect to internet

**Comment by stevespringett** [comment] 2020-03-26 16:07
Duplicate of #42 
Workaround:
```
mvn -DSPDXParser.OnlyUseLocalLicenses=true org.cyclonedx:cyclonedx-maven-plugin:1.6.4:makeAggregateBom
```
or
```
mvn -DSPDXParser.OnlyUseLocalLicenses=true org.cyclonedx:cyclonedx-maven-plugin:1.6.4:makeBom
```

**Closed by stevespringett** 2020-03-26 16:07 UTC
